### ISSUE TITLE
routingkit binary not found

### ISSUE THREAD

**Issue by khangthinh-huynh19** [nextmv-io/nextplot#4]
I want to plot the route of vehicles with the support of routingkit. After installing GO language in Ubuntu (Linux), I run the command in the terminal

`go install github.com/nextmv-io/go-routingkit/cmd/routingkit@latest`

Next, I download the osm data of Kansai Japan with the json file of kyoto-route. However, when I run the command line

```
nextplot route \
        --input_route data/kyoto-route.json \
        --jpath_route "vehicles[*].route" \
        --jpath_x "position.lon" \
        --jpath_y "position.lat" \
        --output_map kyoto-route.html \
        --output_image kyoto-route.png \
        --rk_osm kansai-latest.osm.pbf
```

The system announce that the "routingkit binary not found"

I have reinstalled the Go language and the routingkit but the problem still not be solved.

How can I fix this error ? Thank you for helping.

![image](https://github.com/nextmv-io/nextplot/assets/95524468/3d1d426f-6235-4c7b-a1bb-784f37e67ab6)

**Comment by larsbeck** [comment]
@khangthinh-huynh19 The `routingkit` binary got installed in a subfolder under your profile. This folder is not in your `PATH`. You can either add that folder to your `PATH` or you can install `routingkit` in a folder that is known to your path. For Ubuntu you can do something like:
```bash
GOBIN=/usr/local/bin/ go install github.com/nextmv-io/go-routingkit/cmd/routingkit@latest
```
This will put the `routingkit` binary into `/usr/local/bin` which most likely is in your `PATH` environment variable. In case the above command fails due to insufficient permissions, try as `sudo`:
```bash
sudo GOBIN=/usr/local/bin/ go install github.com/nextmv-io/go-routingkit/cmd/routingkit@latest
```
Hope this helps!

**Comment by khangthinh-huynh19** [comment]
> @khangthinh-huynh19 The `routingkit` binary got installed in a subfolder under your profile. This folder is not in your `PATH`. You can either add that folder to your `PATH` or you can install `routingkit` in a folder that is known to your path. For Ubuntu you can do something like:
> 
> ```shell
> GOBIN=/usr/local/bin/ go install github.com/nextmv-io/go-routingkit/cmd/routingkit@latest
> ```
> 
> This will put the `routingkit` binary into `/usr/local/bin` which most likely is in your `PATH` environment variable. In case the above command fails due to insufficient permissions, try as `sudo`:
> 
> ```shell
> sudo GOBIN=/usr/local/bin/ go install github.com/nextmv-io/go-routingkit/cmd/routingkit@latest
> ```
> 
> Hope this helps!

It 100% works!!!!! Thank you very much for your help!! Hope you have a good working week <3

**Comment by larsbeck** [comment]
Nice, we'll adjust the `README` accordingly. Have a good week!
