### ISSUE TITLE
`routingkit` "installation" link 404 - page not found

### ISSUE THREAD

**Issue by cnpryer** [nextmv-io/nextplot#5]
In https://github.com/nextmv-io/nextplot/blob/develop/examples/README.md#additional-information 

> rk_bin (route only): Path to the [go-routingkit](https://github.com/nextmv-io/nextplot/blob/develop/examples/go-rk) standalone binary. Alternatively, routingkit command will be used at default (requires go-routingkit [installation](https://github.com/nextmv-io/nextplot/blob/develop/examples/go-rk-install)).

The [installation link](https://github.com/nextmv-io/nextplot/blob/develop/examples/go-rk-install) points to a missing page:
<img width="1800" alt="image" src="https://github.com/nextmv-io/nextplot/assets/14341145/496cd5a4-2b20-45d2-8cac-3a9b2abccac8">

**Comment by cnpryer** [comment]
Note [go-routingkit](https://github.com/nextmv-io/nextplot/blob/develop/examples/go-rk) link doesn't work either.

**Comment by merschformann** [comment]
Good catch. Thank you for reporting! :hugs: 

Will be fixed by #6
